@HostAddress = https://localhost:44387/

###

POST {{HostAddress}}/api/execute/roman/math/add/1.0.0.0
Content-Type: application/text

I+II+III  


POST {{HostAddress}}/api/execute/echo/echo/echo/echo
Content-Type: application/text

I+II+III  




####
POST {{HostAddress}}/api/math/add/1.0.0.0/BinaryTenant
Content-Type: application/text

1+1+0
