# For more info on HTTP files go to https://aka.ms/vs/httpfile

#    endpoints.MapPost("/api/execute/{commandName}/{actionName}/{version?}/{tenantId?}/{inputFormat?}/{outputFormat?}", async context =>
      
@HostAddress = http://localhost:5038
# POST Request
POST http://localhost:5038/api/execute/Math/Add/1.0.0.0/RomanTenant
Content-Type: application/text

I+II+III  


# Post V2
POST http://localhost:5038/api/execute/Math/Add/2.0.0.0/RomanTenant
Content-Type: application/text

I+II+III  


###
POST http://localhost:5038/api/execute/echo/echo/echo/echo
Content-Type: application/text

I+II+III  

####
POST http://localhost:5000/api/math/add/1.0.0.0/BinaryTenant
Content-Type: application/text

1+1+0





# GET Request
GET http://localhost:5000/api/products
Content-Type: application/json
Authorization: Bearer <your_token_here>

###

# POST Request
POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "New Product",
  "price": 19.99,
  "description": "A cool new product"
}

###

# PUT Request
PUT http://localhost:5000/api/products/1
Content-Type: application/json

{
  "name": "Updated Product",
  "price": 29.99,
  "description": "Updated description"
}

###

# DELETE Request
DELETE http://localhost:5000/api/products/1

